# Generated by Django 3.2.7 on 2022-02-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('due_date', models.DateTimeField(blank=True)),
                ('importance', models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'HIGH')], max_length=1)),
                ('finished', models.BooleanField(default=False)),
            ],
        ),
    ]
