# Generated by Django 3.2.7 on 2022-02-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_alter_todo_usr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='importance',
            field=models.CharField(choices=[('!', 'Low'), ('!!', 'Medium'), ('!!!', 'High')], max_length=3),
        ),
    ]
