# Generated by Django 3.2.7 on 2022-02-12 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todolist', '0002_auto_20220211_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='usr',
        ),
        migrations.RemoveField(
            model_name='user',
            name='todo_items',
        ),
        migrations.AddField(
            model_name='todo',
            name='user',
            field=models.ManyToManyField(to='todolist.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='usr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
