# Generated by Django 3.2.7 on 2022-02-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_auto_20220212_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='time_since_modified',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=50, unique_for_date='due_date'),
        ),
    ]
