# Generated by Django 3.2.7 on 2022-02-16 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todolist', '0010_todo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='user_last_change',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lastly_changed', to=settings.AUTH_USER_MODEL),
        ),
    ]
