# Generated by Django 3.2.7 on 2022-02-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0012_alter_todo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='image',
            field=models.FileField(default='todo.jpeg', upload_to='todo_attachments'),
        ),
    ]
