# Generated by Django 3.2.7 on 2022-02-19 10:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_auto_20220216_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 10, 51, 6, 365201, tzinfo=utc), null=True),
        ),
    ]
