# Generated by Django 3.2.7 on 2022-02-19 16:41

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_alter_workout_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reps',
            name='workout',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gym.workout'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 16, 41, 11, 743153, tzinfo=utc), null=True),
        ),
    ]
