# Generated by Django 3.2.7 on 2022-02-19 16:47

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0006_auto_20220219_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reps',
            name='workout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gym.workout'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 19, 16, 47, 54, 59696, tzinfo=utc), null=True),
        ),
    ]
