# Generated by Django 3.2.7 on 2022-02-20 09:48

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0008_auto_20220219_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reps',
            name='workout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gym.workout'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 20, 9, 48, 29, 684179, tzinfo=utc), null=True),
        ),
    ]
