# Generated by Django 3.2.7 on 2022-02-20 14:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0010_auto_20220220_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='muscle',
            field=models.CharField(choices=[('Back', 'Back'), ('Chest', 'Chest'), ('Shoulders', 'Shoulders'), ('Legs', 'Legs'), ('Bicep', 'Bicep'), ('Tricep', 'Tricep'), ('Forearm', 'Forearm')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 20, 14, 36, 14, 358229, tzinfo=utc), null=True),
        ),
    ]
