# Generated by Django 3.2.7 on 2022-02-21 10:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0013_auto_20220221_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='exercise_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 2, 21, 10, 42, 28, 244853, tzinfo=utc), null=True),
        ),
    ]
